on:
  push:
    branches:
    # Limit to the `master` branch
    - master
  schedule:
    # Run daily
    - cron:  '0 0* * *'
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate GitHub Pages
      run: |
        # Configure Git for the push from the workflow to the repository
        git config --global user.email "tomas@hubelbauer.net"
        git config --global user.name "Tomas Hubelbauer"
        # Check out the `master` branch because by default GitHub Actions checks out detached HEAD
        git checkout master
        # Generate the file
        mkdir -p data
        name=$(date -Iseconds | sed 's/:/-/g').json
        curl -o $name "https://api.github.com/search/repositories?q=language:csharp+stars:>1000&sort=stars&order=desc"
        $name >> data/index.log
        # Add the changed file to Git stage and ditch extra files (caches, artifacts, …)
        git add data
        git checkout -- .
        # Commit the changes to the Git repository to deploy GitHub Pages (if any)
        if git diff-index --quiet HEAD --; then
          exit
        fi
        git commit -m "Generate GitHub Pages"
        # Use the out of the box PAT even though it won't deploy GitHub Pages
        git remote set-url origin https://tomashubelbauer:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        # Pull before pushing to integrate fast forward changes if any
        git pull
        # Push the changes to GitHub
        git push
