on:
  push:
    branches:
    # Limit to the `master` branch
    - master
  schedule:
    # Run daily at midnight
    - cron:  '0 0 * * *'
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate GitHub Pages
      run: |
        # Configure Git for the push from the workflow to the repository
        git config --global user.email "tomas@hubelbauer.net"
        git config --global user.name "Tomas Hubelbauer"
        # Check out the `master` branch because by default GitHub Actions checks out detached HEAD
        git checkout master
        # Build the CRA app
        cd cra
        npm install
        npm run build
        cd ..
        mv docs/data data
        rm -rf docs
        mv cra/build docs
        mv data docs/data
        # Generate the file
        npm install
        npm start ${{secrets.GITHUB_TOKEN}}
        git add docs
        git checkout -- .
        # Commit the changes to the Git repository to deploy GitHub Pages (if any)
        if git diff-index --quiet HEAD --; then
          exit
        fi
        git commit -m "Generate GitHub Pages"
        # Use the out of the box PAT even though it won't deploy GitHub Pages
        git remote set-url origin https://tomashubelbauer:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
        # Pull before pushing to integrate fast forward changes if any
        git pull
        # Push the changes to GitHub
        git push
        # Enqueue a GitHub Pages deployment using the API with the custom PAT
        curl -f -X POST -H "Authorization: token ${{secrets.GITHUB_PAGES_PAT}}" -H "Accept: application/vnd.github.mister-fantastic-preview+json" "https://api.github.com/repos/${{github.repository}}/pages/builds"
